jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.11
        environment:
          TERRAFORM_VERSION: v0.11
    steps:
      - checkout
      - run:
          command: terraform init
  test:
    docker:
      - image: hashicorp/terraform:0.11.11
    steps:
      - checkout
      - run:
          command: |
            terraform fmt -check=true
            terraform validate
            go test -v ./...
version: 2
workflows:
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
  version: 2
