jobs:
  build:
    docker:
      - image: circleci/golang:1.13.4
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test
orbs:
  go: circleci/go@0.2.0
version: 2.1
workflows:
  default:
    jobs:
      - build
  version: 2
