jobs:
  build:
    executor: default
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          command: |
            wget --quiet https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
            sudo unzip -D /usr/local/bin terraform_0.11.14_linux_amd64.zip
          name: Install Terraform
      - go/test
  release:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - restore_cache:
          key: npm-cache
      - run: npm install @semantic-release/changelog -D
      - run: npm install @semantic-release/git -D
      - run: npx semantic-release
      - save_cache:
          key: npm-cache
          paths:
            - node_modules
orbs:
  go: circleci/go@0.2.0
version: 2.1
workflows:
  default:
    jobs:
      - build
      - release:
          filters:
            branches:
              only: master
          requires:
            - build
  version: 2
